### ISSUE TITLE
Trigger a type error when caller to setup* is providing unknown props

### ISSUE THREAD

**Issue by MattSchiller** [Codecademy/component-test-setup#13]
It would help with keeping tests from getting stale if when the props interface on the component is updated, the `setup*` calls also flagged that you no longer want/need a useless prop.

**Comment by JoshuaKGoldberg** [comment]
Err, I think this already happens? `setup*` _should_ be strongly enough typed that excess props would trigger extra object literal detection in TypeScript. Can you post a code snippet showing this to not be the case?

**Comment by MattSchiller** [comment]
Huh, I guess you're right! I must've been looking at older patterns that had the stale props, so when we move over to the new `setup*`, I can't replicate it.

Dope =)
