### ISSUE TITLE
Allow updating of props (and similar) in a simpler way

### ISSUE THREAD

**Issue by MattSchiller** [Codecademy/component-test-setup#14]
## The Problem: Updating component props is annoying and different across RTL & Enzyme
When you have a component and you'd like to test its behavior over time and as props change (like if you were testing something in a `useEffect` hook or similar), you have:
- Divergent APIs across enzyme and RTL (`wrapper.setProps()` & `view.rerender()` respectively)
- APIs that update props differently (`rerender()` notoriously requires you to re-provide the underlying component and a set of all props, not just the delta of what's changed
Ex:
```ts
        const {
          view: { rerender, getByTestId },
        } = renderView();

        let newProps: PlanInvitationsProps = {
          ...defaultProps,
          planInvitations: {
            ...defaultProps.planInvitations,
            sort: 'asc',
            sortColumn: 'email',
          },
        };

        rerender(<PlanInvitations {...newProps} />);
 ```

_(There are likely more pain points in the gaps that the current API provides, so please feel free to comment with more!)_

## Goals
By creating a layer of abstraction that hides this divergent complexity between these two libraries, we can:
- Empower developers to write tests that are terse and clear in what they're trying to test for
- Reduce the overhead for developers who want to work in/convert-from one underlying test library to another

## Proposed Implementation
Using a fairly straightforward adapter layer that's re-using its known scope should allow us to do this. Something like:

(assume new method is called `updateProps`)

```ts
// in setupEnzyme
  return function renderWrapper(
    testProps?: RemainingPropsAndTestOverrides<ComponentType, BaseProps>,
  ) {
    const props = {
      ...baseProps,
      ...testProps,
    } as FullProps<ComponentType>;
    const wrapper = mount(<Component {...(props as any)} />);

    return { props, wrapper, updateProps: wrapper.setProps };
  };
}

// in setupRtl:
  function renderView(testProps?: RemainingPropsAndTestOverrides<ComponentType, BaseProps>) {
    const props = {
      ...baseProps,
      ...testProps,
    } as FullProps<ComponentType>;
    const view = render(<Component {...(props as any)} />, options);

    const updateProps = (updatedProps: Partial<FullProps<ComponentType>>) =>
      view.rerender(<Component {...(props as any)} {...updatedProps} />);

    return { props, view, updateProps };
  }
```

If we really want to, we can wrap both in an `async` function that makes `act()` an automatic inclusion so callers have to juggle even less boilerplate/overhead.

## Other stuff
Are there other aspects of the CTS that you find clunky and divergent across the two main patterns? Please add them down here (or create a separate issue if you think it warrants it!)

**Comment by ZackMFleischman** [comment]
> If we really want to, we can wrap both in an async function that makes act() an automatic inclusion so callers have to juggle even less boilerplate/overhead.

Looks like this already is wrapped internally for both [RTL](https://github.com/testing-library/react-testing-library/blob/7c84fa39602120e0b2d23a8898af9f3585f39c31/src/pure.js#L59) and [Enzyme](https://github.com/enzymejs/enzyme#reacttestutilsact-wrap).

Only enzyme's `.prop() and .props()` methods are not wrapped, but you can get around this with `.invoke()`.

**Comment by JoshuaKGoldberg** [comment]
**Enzyme** puts component updating into `update()` for both [mount](https://enzymejs.github.io/enzyme/docs/api/ReactWrapper/update.html) and [shallow](https://enzymejs.github.io/enzyme/docs/api/ShallowWrapper/update.html):

```tsx
const wrapper = mount(<ImpureRender />);
expect(wrapper.text()).to.equal('0');
wrapper.update();
expect(wrapper.text()).to.equal('1');
```

...with this note:

> NOTE: this does not force a re-render. Use `wrapper.setProps({})` to force a re-render.

**RTL** does both with [`rerender`](https://testing-library.com/docs/react-testing-library/api/):

```tsx
const { rerender } = render(<NumberDisplay number={1} />);
rerender(<NumberDisplay number={2} />);
```

Since RTL is closer and `rerender` _(with props)_ is what we generally are thinking of, I think my naming preference would be:
1. `rerender(newProps?)`
2. `update(newProps?)`

Love those single-word API names. 😁 

Regardless of what the name is, +1 from me on going ahead and doing it!

**Comment by MattSchiller** [comment]
> Since RTL is closer and `rerender` _(with props)_ is what we generally are thinking of, I think my naming preference would be:
> 
> 1. `rerender(newProps?)`
> 2. `update(newProps?)`

I'll probably end up going with `update`, since I actually don't want to confuse people whenever they have to use the native `rerender` (they shouldn't if using this, but still).

Getting right on this!
